name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Test against LTS and current
      fail-fast: false  # Continue with other versions if one fails

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Verify package-lock.json
      run: |
        npm install --package-lock-only
        git diff --exit-code package-lock.json || (echo "package-lock.json is out of sync" && exit 1)
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run CI checks
      run: npm run ci
