name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: 1

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]  # Current LTS version
      fail-fast: false  # Continue with other versions if one fails

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Verify package-lock.json
      run: |
        npm install --package-lock-only --ignore-scripts
        git diff --exit-code package-lock.json || (echo "package-lock.json is out of sync" && exit 1)
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run Validation (type-check, tests with coverage, lint)
      run: npm run ci
      
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 14
