name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x, 24.x]
      fail-fast: false  # Continue with other versions if one fails

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        # Temporarily disable cache to rule out cache-related lockfile issues
        # cache: npm
        # cache-dependency-path: package-lock.json

    - name: Report Node and npm versions
      run: |
        echo "=== Node/npm versions ==="
        node -v
        npm -v
        echo "=== npm cache path ==="
        npm config get cache

    - name: Pin npm to version 11 (matching local environment)
      run: |
        npm install -g npm@11
        echo "Pinned npm to: $(npm -v)"

    - name: Clear npm cache
      run: |
        npm cache clean --force
        echo "Cache cleaned"
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run Validation (type-check, tests with coverage, lint)
      run: npm run ci
