name: Coverage Report

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  FORCE_COLOR: 1

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm test
      
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 14
    
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'Coverage Report'
    
    - name: Extract coverage info
      id: extract-coverage
      run: |
        STATEMENTS=$(jq -r '.total.statements.pct' coverage/coverage-summary.json)
        BRANCHES=$(jq -r '.total.branches.pct' coverage/coverage-summary.json)
        FUNCTIONS=$(jq -r '.total.functions.pct' coverage/coverage-summary.json)
        LINES=$(jq -r '.total.lines.pct' coverage/coverage-summary.json)
        
        echo "statements=$STATEMENTS" >> $GITHUB_OUTPUT
        echo "branches=$BRANCHES" >> $GITHUB_OUTPUT
        echo "functions=$FUNCTIONS" >> $GITHUB_OUTPUT
        echo "lines=$LINES" >> $GITHUB_OUTPUT
        
        # Check if coverage thresholds are met
        THRESHOLDS_MET=true
        if (( $(echo "$STATEMENTS < 75" | bc -l) )); then THRESHOLDS_MET=false; fi
        if (( $(echo "$BRANCHES < 75" | bc -l) )); then THRESHOLDS_MET=false; fi
        if (( $(echo "$FUNCTIONS < 75" | bc -l) )); then THRESHOLDS_MET=false; fi
        if (( $(echo "$LINES < 75" | bc -l) )); then THRESHOLDS_MET=false; fi
        
        echo "thresholds_met=$THRESHOLDS_MET" >> $GITHUB_OUTPUT
    
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Coverage Report
          
          | Metric | Coverage | Threshold | Status |
          | ------ | -------- | --------- | ------ |
          | Statements | ${{ steps.extract-coverage.outputs.statements }}% | 75% | ${{ steps.extract-coverage.outputs.statements >= 75 && '✅' || '❌' }} |
          | Branches | ${{ steps.extract-coverage.outputs.branches }}% | 75% | ${{ steps.extract-coverage.outputs.branches >= 75 && '✅' || '❌' }} |
          | Functions | ${{ steps.extract-coverage.outputs.functions }}% | 75% | ${{ steps.extract-coverage.outputs.functions >= 75 && '✅' || '❌' }} |
          | Lines | ${{ steps.extract-coverage.outputs.lines }}% | 75% | ${{ steps.extract-coverage.outputs.lines >= 75 && '✅' || '❌' }} |
          
          ${{ steps.extract-coverage.outputs.thresholds_met == 'true' && '✅ All coverage thresholds met!' || '❌ Some coverage thresholds not met. Please improve test coverage.' }}
          
          [View detailed coverage report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        edit-mode: replace
        reactions: eyes
