name: Dependency Update Test

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
    branches: [ main ]

jobs:
  test-dependency-update:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint validation
      run: npm run lint
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run tests with coverage
      run: npm test
      
    - name: Check for ESLint peer dependency warnings
      run: |
        # Run npm ls to check for peer dependency warnings
        OUTPUT=$(npm ls @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint 2>&1)
        echo "$OUTPUT"
        
        # Check if there are unexpected peer dependency issues (beyond the known ones)
        if echo "$OUTPUT" | grep -i "UNMET PEER DEPENDENCY" | grep -v "eslint@8"; then
          echo "Unexpected peer dependency issues found!"
          exit 1
        else
          echo "Only expected peer dependency warnings found, proceeding."
        fi
      
    - name: Validate ESLint configuration
      run: npx eslint --print-config eslint.config.js > /dev/null
