name: Update Coverage Badge

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm test
      
    - name: Extract coverage info
      id: extract-coverage
      run: |
        LINES=$(jq -r '.total.lines.pct' coverage/coverage-summary.json)
        # Round to nearest integer
        LINES_ROUNDED=$(printf "%.0f" $LINES)
        echo "lines=$LINES_ROUNDED" >> $GITHUB_OUTPUT
        
        # Determine badge color based on coverage
        if (( $(echo "$LINES_ROUNDED >= 90" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$LINES_ROUNDED >= 80" | bc -l) )); then
          COLOR="green"
        elif (( $(echo "$LINES_ROUNDED >= 70" | bc -l) )); then
          COLOR="yellowgreen"
        elif (( $(echo "$LINES_ROUNDED >= 60" | bc -l) )); then
          COLOR="yellow"
        else
          COLOR="red"
        fi
        echo "color=$COLOR" >> $GITHUB_OUTPUT
    
    - name: Update README badge
      run: |
        COVERAGE="${{ steps.extract-coverage.outputs.lines }}"
        COLOR="${{ steps.extract-coverage.outputs.color }}"
        
        # Replace the coverage badge in README.md
        sed -i "s|https://img.shields.io/badge/Coverage-[0-9]\+%25-[a-z]\+.svg|https://img.shields.io/badge/Coverage-${COVERAGE}%25-${COLOR}.svg|g" README.md
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "docs: update coverage badge to ${COVERAGE}%"
          git push
        fi
